### ISSUE TITLE
mypy validation fails as of 0.35.0

### ISSUE THREAD

**Issue by lotus-kefir** [rnag/dataclass-wizard#176]
Switching from v0.34.0 -> v0.35.0 starts raising this error:

```py
mypy run-test: commands[1] | mypy --config-file tox.ini test_proj
.tox/mypy/lib/python3.9/site-packages/dataclass_wizard/wizard_mixins.pyi:20: error:
invalid syntax 
[syntax]
    type FileType = str | bytes | PathLike
          ^
Found 1 error in 1 file (errors prevented further checking)
```

I checked pip was on newest for both, didn't seem to make a difference.

Minimal reproduction:

`test_proj/main.py`
```py
import dataclass_wizard

print('ok')
```

`pyproject.toml`
```toml
[project]
name = "test_proj"
requires-python = ">=3.9"
dynamic = ["version", "dependencies", "optional-dependencies"]

[tool.vulcan]
packages = ["test_proj"]
no-lock = true

[tool.vulcan.dependencies]
# Change between 34 & 35
dataclass-wizard = "==0.35.0"

[tool.vulcan.extras]
build_static_analysis = [
    "mypy~=1.14",
]

[tool.setuptools.dynamic.version]
file = "VERSION"

[tool.setuptools.packages.find]
include = ["test_proj"]

[build-system]
requires = [ "vulcan-py~=2.0" ]
build-backend = "vulcan.build_backend"
```

`tox.ini`
```ini
[tox]
requires = 
	tox < 4.0
	tox >= 3.22
envlist = mypy, flake8, wheel,test
isolated_build = True

[testenv]
recreate = true
basepython = python3.9
passenv = bamboo_*
platform = 
	linux: linux
allowlist_externals = 
	/bin/mkdir
; I use a different internal index_url + trusted_host, other than that no changes
install_command = pip install --no-compile --disable-pip-version-check {packages}

[testenv:mypy]
extras = build_static_analysis
commands = 
    pip install --upgrade pip
	mypy --config-file tox.ini test_proj

[mypy]
show_error_codes = True
pretty = True
```

Run with 

```sh
python3.9 -m venv .venv; source .venv/bin/activate.fish; pip install --upgrade pip; 
pip install -e .
tox -e mypy
```
